clc
clear all

CSVDir = '..\Results\ROIbyROI\';
CSVsList = dir(char(strcat(CSVDir, '*Measures.csv')));
sizeTotal = length(CSVsList);
 

Results{sizeTotal, 104} = 0;

for i=1:sizeTotal
   
    clear filename A
    filename = strcat(CSVsList(i).folder, '\', CSVsList(i).name);
    name = char(CSVsList(i).name);
    A = readmatrix(filename);
    
    strings = strsplit(name, '-');
    infos = [str2num(char(strings(1))), str2num(char(strings(2))), ...
        str2num(char(strings(3))), str2num(char(strings(4)))];
    
    r = [A(6, :), A(2, :), A(7, :), A(3, :), ...
        A(8, :), A(4, :), A(9, :), A(5, :),A(10, :)];
    
    [i, size(infos), size(r)]
    
    values = [infos, A(1, :),  r];
    
    for j=1:104
        Results{i, j } = values(j);
    end
end

T =  cell2table(Results);



T.Properties.VariableNames = {'DatasetIdx','ExamNum','ROI','Annotation', ...
    'FastGrowCut1-MCC', 'FastGrowCut1-AUC', 'FastGrowCut1-HD', 'FastGrowCut1-Accuracy', ...
    'FastGrowCut1-Precision', 'FastGrowCut1-Sensistivity', 'FastGrowCut1-Specificity', ...
    'FastGrowCut1-F-Measure', 'FastGrowCut1-AVD', 'FastGrowCut1-RunTime', 'FastGrowCut2-MCC', 'FastGrowCut2-AUC', ...
    'FastGrowCut2-HD', 'FastGrowCut2-Accuracy', ...
    'FastGrowCut2-Precision', 'FastGrowCut2-Sensistivity', 'FastGrowCut2-Specificity', ...
    'FastGrowCut2-F-Measure', 'FastGrowCut2-AVD', 'FastGrowCut2-RunTime'...
    'FastCleverSeg1-MCC', 'FastCleverSeg1-AUC', 'FastCleverSeg1-HD', 'FastCleverSeg1-Accuracy', ...
    'FastCleverSeg1-Precision', 'FastCleverSeg1-Sensistivity', 'FastCleverSeg1-Specificity', ...
    'FastCleverSeg1-F-Measure', 'FastCleverSeg1-AVD', 'FastCleverSeg1-RunTime', 'FastCleverSeg2-MCC', 'FastCleverSeg2-AUC', ...
    'FastCleverSeg2-HD', 'FastCleverSeg2-Accuracy', ...
    'FastCleverSeg2-Precision', 'FastCleverSeg2-Sensistivity', 'FastCleverSeg2-Specificity', ...
    'FastCleverSeg2-F-Measure', 'FastCleverSeg2-AVD', 'FastCleverSeg2-RunTime',...
    'CleverSeg1-MCC', 'CleverSeg1-AUC', 'CleverSeg1-HD', 'CleverSeg1-Accuracy', ...
    'CleverSeg1-Precision', 'CleverSeg1-Sensistivity', 'CleverSeg1-Specificity', ...
    'CleverSeg1-F-Measure', 'CleverSeg1-AVD', 'CleverSeg1-RunTime', 'CleverSeg2-MCC', 'CleverSeg2-AUC', ...
    'CleverSeg2-HD', 'CleverSeg2-Accuracy', ...
    'CleverSeg2-Precision', 'CleverSeg2-Sensistivity', 'CleverSeg2-Specificity', ...
    'CleverSeg2-F-Measure', 'CleverSeg2-AVD', 'CleverSeg2-RunTime',...
    'BGrowth1-MCC', 'BGrowthSeg1-AUC', 'BGrowth1-HD', 'BGrowth1-Accuracy', ...
    'BGrowth1-Precision', 'BGrowth1-Sensistivity', 'BGrowth1-Specificity', ...
    'BGrowth1-F-Measure', 'BGrowth1-AVD', 'BGrowth1-RunTime', 'BGrowth2-MCC', 'BGrowth2-AUC', ...
    'BGrowth2-HD', 'BGrowth2-Accuracy', ...
    'BGrowth2-Precision', 'BGrowth2-Sensistivity', 'BGrowth2-Specificity', ...
    'BGrowth2-F-Measure', 'BGrowth2-AVD', 'BGrowth2-RunTime',...
     'GrowCut1-MCC', 'GrowCut1-AUC', 'GrowCut1-HD', 'GrowCut1-Accuracy', ...
    'GrowCut1-Precision', 'GrowCut1-Sensistivity', 'GrowCut1-Specificity', ...
    'GrowCut1-F-Measure', 'GrowCut1-AVD', 'GrowCut1-RunTime', 'GrowCut2-MCC', 'GrowCut2-AUC', ...
    'GrowCut2-HD', 'GrowCut2-Accuracy', ...
    'GrowCut2-Precision', 'GrowCut2-Sensistivity', 'GrowCut2-Specificity', ...
    'GrowCut2-F-Measure', 'GrowCut2-AVD', 'GrowCut2-RunTime'};

writetable(T, '..\Results\ResultsAll.csv');